# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  gateway-sonar:
    image: sonarqube:9.6.0-community
    # Authentication is turned off for out of the box experience while trying out SonarQube
    # For real use cases delete sonar.forceAuthentication variable or set sonar.forceAuthentication=true
    environment:
      - sonar.forceAuthentication=false

    ports:
      - 9001:9000
